# Generated by Django 4.2.6 on 2023-11-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dateapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='um',
            name='mesages',
            field=models.ManyToManyField(blank=True, related_name='chatroom_messages', to='dateapp.message'),
        ),
    ]
