# Generated by Django 4.2.6 on 2023-11-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dateapp', '0002_um_mesages'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='choosedpref',
            field=models.BooleanField(default=False),
        ),
    ]
