# Generated by Django 4.2.6 on 2023-11-17 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dateapp', '0003_user_choosedpref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='um',
            name='mesages',
        ),
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL)),
                ('mesages', models.ManyToManyField(blank=True, related_name='chatroom_messages', to='dateapp.message')),
            ],
        ),
    ]
