# Generated by Django 4.2.6 on 2023-11-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dateapp', '0004_remove_um_mesages_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interestingsex',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
